
FROM alpine:latest

WORKDIR /home

RUN apk add --no-cache wget clang make

RUN wget https://code.call-cc.org/releases/5.4.0/chicken-5.4.0.tar.gz --no-verbose && \
	tar xf chicken-5.4.0.tar.gz && cd chicken-5.4.0 && \
	make C_COMPILER=clang LINKER=clang && \
	make C_COMPILER=clang LINKER=clang install && \
	cd .. && rm -rf chicken-5.4.0*

