
build:
	docker build -t massimonocentini/chicken-scheme:5.4.0-clang-alpine -f Dockerfile.alpine .

myeggs:
	docker build -t massimonocentini/chicken-scheme:5.4.0-clang-myeggs-alpine -f Dockerfile.myeggs .

run:
	docker run -it --rm massimonocentini/chicken-scheme:5.4.0-clang-alpine
